version: "3.1"

services:
  mongo:
    image: mongo:bionic
    ports:
      - "27017:27017"
    volumes:
      - ./docker-scripts/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./db-dump:/db-dump
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  impc-bulk-api:
    build:
      context: .
      dockerfile: Dockerfile-local
    environment:
      IMPC_MONGO_URI: mongodb://admin:password@mongo:27017
      IMPC_MONGO_DB: impc
    ports:
      - "8080:8080"
    depends_on:
      - mongo
