apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: impc-api-service-dev
  name: impc-api-service-dev
  namespace: mi-pa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impc-api-service-dev
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: impc-api-service-dev
    spec:
      containers:
        - image: mouse-informatics/impc-mousephenotype-api:latest
          imagePullPolicy: Always
          name: impc-api-service-dev
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /production-tracker-dev-api
            - name: TRACKER_POSTGRESQL_DB_HOST
              value: production-tracker-dev-database
            - name: TRACKER_POSTGRESQL_DB_PORT
              value: "5432"
            - name: REDEPLOY_KEY
              value: "STRING_REPLACED_DURING_REDEPLOY"
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
