apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: impc-mousephenotype-api-dev
  namespace: mi-pa-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: impc-mousephenotype-api-dev
    spec:
      containers:
        - name: impc-mousephenotype-api-dev
          image: "mouse-informatics/impc-mousephenotype-api:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: impc-mousephenotype-api-dev
  namespace: mi-pa-test
  labels:
    name: impc-mousephenotype-api-dev
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: impc-mousephenotype-api-dev
  type: NodePort
