apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: impc-api-service-dev
  name: impc-api-service-dev
  namespace: mi-pa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impc-api-service-dev
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: impc-api-service-dev
    spec:
      imagePullSecrets:
        - name: impcapiregistrycredentials
      containers:
        - image: dockerhub.ebi.ac.uk/mouse-informatics/impc-mousephenotype-api:latest
          imagePullPolicy: Always
          name: impc-api-service-dev
          env:
            - name: IMPC_API_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_password
          envFrom:
            - configMapRef:
                name: database-conn
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}

