apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: impc-mousephenotype-api-service-dev
  name: impc-mousephenotype-api-service-dev
  namespace: mi-pa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impc-mousephenotype-api-service-dev
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: impc-mousephenotype-api-service-dev
    spec:
      imagePullSecrets:
        - name: impcapiregistrycredentials
      containers:
        - image: dockerhub.ebi.ac.uk/mouse-informatics/impc-mousephenotype-api:latest
          imagePullPolicy: Always
          name: impc-mousephenotype-api-service-dev
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /impc-dev-api
            - name: IMPC_API_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db_password
            - name: REDEPLOY_KEY
              value: "STRING_REPLACED_DURING_REDEPLOY"
          envFrom:
            - configMapRef:
                name: database-conn
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 60
          resources: {}

